version: '3.1'

services:

  tomcat-birt:
    build: ./tomcat-birt
    container_name: tomcat-birt

    restart: always
    volumes:
      - ./tomcat-birt/logging.properties:/usr/local/tomcat/conf/logging.properties
      - ./tomcat-birt/server.xml:/usr/local/tomcat/conf/server.xml

  nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
      - "443:443"
#    environment:
#      - NGINX_HOST=up-server.cf
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/tomcat.conf
      - ./certbot/web-root:/var/www/html
      - ./certbot/certbot-etc:/etc/letsencrypt
      - ./certbot/certbot-var:/var/lib/letsencrypt
    depends_on:
      - "tomcat-birt"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/certbot-etc:/etc/letsencrypt
      - ./certbot/certbot-var:/var/lib/letsencrypt
      - ./certbot/web-root:/var/www/html
    depends_on:
      - "nginx"
    command: certonly --webroot --webroot-path=/var/www/html --email vasil.german@gmail.com --agree-tos --no-eff-email -d up-server.cf  -d www.up-server.cf